"""empty message

Revision ID: a6d8132fca3d
Revises: 39d8918cba61
Create Date: 2019-03-12 15:51:25.070528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d8132fca3d'
down_revision = '39d8918cba61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('gender', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'gender')
    # ### end Alembic commands ###
