"""empty message

Revision ID: fdb4b47e07f3
Revises: d5f24dbcfd3e
Create Date: 2019-03-22 22:44:47.946161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb4b47e07f3'
down_revision = 'd5f24dbcfd3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('shoe_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shoe_id'], ['shoes.id'], ),
    sa.PrimaryKeyConstraint('shoe_id', 'customer_id')
    )
    op.add_column('shoes', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoes', 'quantity')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
